// Sample 2050 scenario data — illustrative, AI-assisted figures for prototype only.
// Real version would be regenerated daily from Eurostat + news/policy analysis.

window.EU2050_DATA = {

  // ---- Country-level data, keyed by ISO3 ----
  countries: {

    // --- Founding / current EU core ---
    "DEU": { name:"Germany", eu:true,
      fragScore:0.55, fedScore:0.95,
      fragNote:"Largest economy, but still bound by national vetoes on energy and tax policy. Industrial base increasingly reliant on imported chips and software platforms.",
      fedNote:"Anchors the federal capital market and co-funds the EU semiconductor and AI compute programme.",
      popFrag:"79M", popFed:"81M" },
    "FRA": { name:"France", eu:true,
      fragScore:0.55, fedScore:0.95,
      fragNote:"Pushes 'strategic autonomy' rhetoric but national defence and energy policy remain largely separate from EU partners.",
      fedNote:"Co-leads federal defence procurement and the EU digital identity & cloud stack.",
      popFrag:"69M", popFed:"71M" },
    "ITA": { name:"Italy", eu:true,
      fragScore:0.45, fedScore:0.85,
      fragNote:"High public debt limits fiscal room; depends on EU transfers without full integration of capital markets to absorb shocks.",
      fedNote:"Benefits from a shared federal debt instrument that lowers borrowing costs and funds green industry.",
      popFrag:"54M", popFed:"55M" },
    "ESP": { name:"Spain", eu:true,
      fragScore:0.5, fedScore:0.88,
      fragNote:"Strong renewables growth, but exports of clean energy to the rest of Europe limited by unfinished interconnections.",
      fedNote:"Becomes a net energy exporter within a unified EU grid and capital market.",
      popFrag:"47M", popFed:"48M" },
    "POL": { name:"Poland", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Frontline state on security policy, but defence spending and procurement remain mostly national.",
      fedNote:"Hosts federal defence-industrial hubs supplying a joint EU force structure.",
      popFrag:"35M", popFed:"36M" },
    "NLD": { name:"Netherlands", eu:true,
      fragScore:0.6, fedScore:0.95,
      fragNote:"Home to critical chip-equipment supply chains, but export controls are negotiated bilaterally with the US, not as one EU bloc.",
      fedNote:"Chip-equipment leadership becomes the technical core of EU semiconductor sovereignty.",
      popFrag:"18.5M", popFed:"19M" },
    "BEL": { name:"Belgium", eu:true,
      fragScore:0.55, fedScore:0.97,
      fragNote:"Hosts EU institutions, but Brussels' coordinating role outpaces actual policy integration.",
      fedNote:"Becomes the administrative and judicial seat of the federal government.",
      popFrag:"12M", popFed:"12.3M" },
    "AUT": { name:"Austria", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Neutrality tradition keeps it outside deeper EU defence integration.",
      fedNote:"Joins a common federal defence framework while retaining a non-aligned diplomatic identity.",
      popFrag:"9.3M", popFed:"9.5M" },
    "SWE": { name:"Sweden", eu:true,
      fragScore:0.55, fedScore:0.9,
      fragNote:"Strong on digital services but its tech sector still depends on US cloud infrastructure.",
      fedNote:"Anchors the EU's sovereign cloud and data-centre network.",
      popFrag:"11.5M", popFed:"11.8M" },
    "FIN": { name:"Finland", eu:true,
      fragScore:0.55, fedScore:0.9,
      fragNote:"NATO member, but EU-level defence-industrial cooperation remains limited.",
      fedNote:"Telecom and cybersecurity expertise feeds the federal digital sovereignty programme.",
      popFrag:"5.5M", popFed:"5.6M" },
    "DNK": { name:"Denmark", eu:true,
      fragScore:0.55, fedScore:0.9,
      fragNote:"Leads on offshore wind, but a unified EU energy market remains incomplete.",
      fedNote:"Offshore wind becomes part of a federation-wide energy grid and capital pool.",
      popFrag:"6.1M", popFed:"6.3M" },
    "IRL": { name:"Ireland", eu:true,
      fragScore:0.45, fedScore:0.8,
      fragNote:"Corporate tax model under strain as national tax competition persists inside the bloc.",
      fedNote:"Adapts to a harmonised federal tax base while retaining a strong digital-services cluster.",
      popFrag:"5.6M", popFed:"5.8M" },
    "PRT": { name:"Portugal", eu:true,
      fragScore:0.45, fedScore:0.82,
      fragNote:"Atlantic-facing data-cable hub, but digital infrastructure investment depends on non-EU capital.",
      fedNote:"Becomes a federal digital gateway, with EU-funded subsea cable and data infrastructure.",
      popFrag:"10M", popFed:"10.3M" },
    "GRC": { name:"Greece", eu:true,
      fragScore:0.4, fedScore:0.8,
      fragNote:"Strategic Eastern Mediterranean position, but still recovering fiscal space limits its EU leverage.",
      fedNote:"Becomes a federal energy and logistics hub linking the EU to the Eastern Mediterranean and Balkans.",
      popFrag:"9.8M", popFed:"10.1M" },
    "CZE": { name:"Czechia", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Strong manufacturing base, but tied to non-EU automotive and battery supply chains.",
      fedNote:"Battery and automotive sector integrates into a federal industrial policy.",
      popFrag:"10.7M", popFed:"11M" },
    "SVK": { name:"Slovakia", eu:true,
      fragScore:0.45, fedScore:0.82,
      fragNote:"Energy dependency on external suppliers remains a vulnerability.",
      fedNote:"Plugged into a federation-wide energy security framework.",
      popFrag:"5.4M", popFed:"5.5M" },
    "HUN": { name:"Hungary", eu:true,
      fragScore:0.35, fedScore:0.6,
      fragNote:"Frequently blocks common EU positions, deepening the bloc's decision-making paralysis.",
      fedNote:"Remains a member but with reduced veto power under federal qualified-majority rules.",
      popFrag:"9.2M", popFed:"9.3M" },
    "ROU": { name:"Romania", eu:true,
      fragScore:0.45, fedScore:0.85,
      fragNote:"Key Black Sea security role, but defence integration with EU partners is still patchy.",
      fedNote:"Becomes a federal frontline hub bordering the newly acceded Moldova and Ukraine.",
      popFrag:"18M", popFed:"18.5M" },
    "BGR": { name:"Bulgaria", eu:true,
      fragScore:0.4, fedScore:0.78,
      fragNote:"Lags on digital infrastructure investment relative to EU peers.",
      fedNote:"Receives federal cohesion funding to close the digital infrastructure gap.",
      popFrag:"5.8M", popFed:"6M" },
    "HRV": { name:"Croatia", eu:true,
      fragScore:0.45, fedScore:0.82,
      fragNote:"Tourism-dependent economy exposed to external shocks with limited EU-level buffers.",
      fedNote:"Adriatic tourism and shipping integrate into a federal single market with shared risk pooling.",
      popFrag:"3.7M", popFed:"3.8M" },
    "SVN": { name:"Slovenia", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Small open economy exposed to fragmented EU capital markets.",
      fedNote:"Gains from a single federal capital market reducing borrowing costs for small economies.",
      popFrag:"2.1M", popFed:"2.15M" },
    "LTU": { name:"Lithuania", eu:true,
      fragScore:0.5, fedScore:0.88,
      fragNote:"Frontline state on Russia border security, reliant on NATO more than EU structures.",
      fedNote:"Integrated into a federal eastern defence shield alongside Poland and Finland.",
      popFrag:"2.6M", popFed:"2.7M" },
    "LVA": { name:"Latvia", eu:true,
      fragScore:0.48, fedScore:0.85,
      fragNote:"Energy grid still synchronising away from non-EU networks.",
      fedNote:"Fully integrated into the federal Baltic energy grid.",
      popFrag:"1.8M", popFed:"1.85M" },
    "EST": { name:"Estonia", eu:true,
      fragScore:0.6, fedScore:0.92,
      fragNote:"Digital governance leader, but its e-government model isn't yet an EU-wide standard.",
      fedNote:"Estonia's digital-ID model becomes the federal standard for all member states.",
      popFrag:"1.4M", popFed:"1.45M" },
    "LUX": { name:"Luxembourg", eu:true,
      fragScore:0.55, fedScore:0.95,
      fragNote:"Financial hub benefits from EU access but national rules still fragment capital flows.",
      fedNote:"Becomes a key node in the unified federal capital markets union.",
      popFrag:"0.75M", popFed:"0.8M" },
    "MLT": { name:"Malta", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Small state with limited leverage over EU-level digital and energy policy.",
      fedNote:"Gains proportionally stronger voice under federal small-state safeguards.",
      popFrag:"0.6M", popFed:"0.62M" },
    "CYP": { name:"Cyprus", eu:true,
      fragScore:0.45, fedScore:0.8,
      fragNote:"Eastern Mediterranean energy finds remain entangled in bilateral disputes.",
      fedNote:"Federal foreign policy resolves regional disputes with a single EU negotiating voice.",
      popFrag:"1M", popFed:"1.05M" },

    // --- Western Balkans: EU 2026, candidate/aspiring; federal-2050 members ---
    "SRB": { name:"Serbia", eu:false,
      fragScore:0.3, fedScore:0.78, fedNew:true,
      fragNote:"Accession talks remain stalled by rule-of-law concerns and balancing act between EU and other powers.",
      fedNote:"Joins the federation by the early 2040s, integrating its energy grid and labour market with the EU.",
      popFrag:"6.4M", popFed:"6.6M" },
    "ALB": { name:"Albania", eu:false,
      fragScore:0.32, fedScore:0.76, fedNew:true,
      fragNote:"Accession process moves slowly; economy remains only loosely linked to the single market.",
      fedNote:"Becomes a federal member state, with tourism and energy sectors fully integrated.",
      popFrag:"2.7M", popFed:"2.8M" },
    "MNE": { name:"Montenegro", eu:false,
      fragScore:0.35, fedScore:0.8, fedNew:true,
      fragNote:"Furthest along in accession talks but full membership remains pending.",
      fedNote:"One of the earliest Balkan accessions, fully part of the federal single market by the 2030s.",
      popFrag:"0.6M", popFed:"0.62M" },
    "MKD": { name:"The former Yugoslav Republic of Macedonia", eu:false,
      fragScore:0.3, fedScore:0.76, fedNew:true,
      fragNote:"Name and constitutional disputes have repeatedly slowed its EU path.",
      fedNote:"Joins the federation, contributing to a fully connected Balkan energy and transport corridor.",
      popFrag:"1.8M", popFed:"1.85M" },
    "BIH": { name:"Bosnia and Herzegovina", eu:false,
      fragScore:0.25, fedScore:0.7, fedNew:true,
      fragNote:"Complex internal governance structure remains the biggest obstacle to EU accession.",
      fedNote:"Joins later than its neighbours, with federal mediation helping resolve internal governance issues.",
      popFrag:"3.2M", popFed:"3.3M" },
    "XKX": { name:"Kosovo", eu:false,
      fragScore:0.25, fedScore:0.68, fedNew:true,
      fragNote:"Recognition gaps among EU member states themselves slow any accession progress.",
      fedNote:"Recognition issues resolved within a federal framework, enabling full integration.",
      popFrag:"1.6M", popFed:"1.7M" },

    // --- Ukraine & Moldova: candidates in 2026; federal-2050 new members ---
    "UKR": { name:"Ukraine", eu:false,
      fragScore:0.2, fedScore:0.75, fedNew:true,
      fragNote:"Reconstruction and accession remain heavily dependent on external (often non-EU) financing and security guarantees.",
      fedNote:"Joins the federation, bringing a large agricultural and tech-talent base and a fully rebuilt, EU-integrated industrial base. EU population grows significantly.",
      popFrag:"33M", popFed:"35M" },
    "MDA": { name:"Republic of Moldova", eu:false,
      fragScore:0.28, fedScore:0.78, fedNew:true,
      fragNote:"Small economy, vulnerable to external pressure while accession talks proceed slowly.",
      fedNote:"One of the fastest accessions, fully integrated into the federal single market and energy grid.",
      popFrag:"2.4M", popFed:"2.5M" },
    "GEO": { name:"Georgia", eu:false,
      fragScore:0.25, fedScore:0.78, fedNew:true,
      fragNote:"EU accession is slowed by geopolitical tensions and domestic reform challenges.",
      fedNote:"Joins the federation as a new eastern member, deepening EU energy and transport links with the South Caucasus.",
      popFrag:"3.7M", popFed:"3.9M" },
    "ARM": { name:"Armenia", eu:false,
      fragScore:0.28, fedScore:0.78, fedNew:true,
      fragNote:"Continues building ties with the EU while balancing relations with Russia and regional security partners.",
      fedNote:"Becomes a federation partner, strengthening EU access to South Caucasus transport and digital corridors.",
      popFrag:"3.0M", popFed:"3.1M" },
    "AZE": { name:"Azerbaijan", eu:false,
      fragScore:0.3, fedScore:0.78, fedNew:true,
      fragNote:"Energy and geopolitical tensions leave its EU path uncertain despite economic interest in closer ties.",
      fedNote:"Enters the federation with strategic energy and transport links to the Caspian and Black Sea regions.",
      popFrag:"10.3M", popFed:"10.7M" },

    // --- Non-EU neighbours / not modelled as part of either scenario's core ---
    "GBR": { name:"United Kingdom", eu:false, fedNew:true,
      fragScore:0.5, fedScore:0.4,
      fragNote:"Remains outside the EU; closer alignment on some standards but no formal reintegration.",
      fedNote:"Stays outside the federation; maintains a close but separate trade and security relationship.",
      popFrag:"70M", popFed:"71M" },
    "CHE": { name:"Switzerland", eu:false,
      fragScore:0.5, fedScore:0.45, fedNew:true,
      fragNote:"Maintains bilateral arrangements rather than full integration.",
      fedNote:"Remains formally outside the federation but deeply linked via bilateral treaties.",
      popFrag:"9.5M", popFed:"9.6M" },
    "NOR": { name:"Norway", eu:false,
      fragScore:0.5, fedScore:0.45, fedNew:true,
      fragNote:"EEA member but outside core EU decision-making on digital and capital markets policy.",
      fedNote:"Energy ties deepen with the federation's grid, though Norway stays outside formal membership.",
      popFrag:"5.7M", popFed:"5.8M" },
    "ISL": { name:"Iceland", eu:false,
      fragScore:0.5, fedScore:0.45, fedNew:true,
      fragNote:"Limited engagement with EU-level integration debates.",
      fedNote:"Remains outside the federation, EEA-linked.",
      popFrag:"0.42M", popFed:"0.43M" },
    "TUR": { name:"Turkey", eu:false,
      fragScore:0.35, fedScore:0.3, fedNew:true,
      fragNote:"Long-frozen accession process; relationship managed through customs union and migration deals.",
      fedNote:"Accession remains off the table; relationship continues via separate strategic partnership.",
      popFrag:"88M", popFed:"90M" }
  },

  // ---- Aggregate scenario stats shown in the stat strips ----
  stats: {
    frag: { pop:"418M", members:"29", tech:"9%" },
    fed:  { pop:"503M", members:"33", tech:"22%" }
  },
  feedUpdated: "19 Jun 2026",

  // ---- Sample AI-generated daily signal feed ----
  // In production this is regenerated daily by an automated pipeline that
  // reads EU news/policy documents and tags each story's likely pull on each scenario.
  feed: [
    {
      date:"18 Jun 2026",
      headline:"EU agrees landmark AI governance roadmap, but implementation timeline remains contested",
      ai:"Commission and member states outline common AI liability and certification rules while national regulators still negotiate enforcement powers.",
      frag:"Highlights ongoing fragmentation in digital regulation",
      fed:"Moves the federation closer to a single EU tech governance framework"
    },
    {
      date:"17 Jun 2026",
      headline:"European Parliament backs strengthened carbon border levy for imported steel and chemicals",
      ai:"A new CBAM proposal seeks tighter enforcement on high-carbon imports, raising pressure on industry and trading partners.",
      frag:"Increases trade tensions under a fractured climate policy regime",
      fed:"Supports the federal green-industrial transition by aligning external carbon pricing"
    },
    {
      date:"16 Jun 2026",
      headline:"EU foreign ministers approve a joint connectivity package for the Western Balkans",
      ai:"Funding and regulatory alignment for cross-border energy and data corridors are agreed, signalling deeper integration with candidate neighbours.",
      frag:"Limited by separate national implementation plans",
      fed:"Accelerates the federation’s eastern enlargement and infrastructure integration"
    },
    {
      date:"15 Jun 2026",
      headline:"Council debates migration and energy solidarity rules ahead of summer peak",
      ai:"Member states are split over mandatory burden-sharing and fast-track renewable power sharing, exposing persistent EU coordination gaps.",
      frag:"Highlights the limits of national-only crisis response",
      fed:"Reinforces the need for a federal emergency energy and asylum framework"
    },
    {
      date:"14 Jun 2026",
      headline:"Council fails to agree on unified chip-export control list",
      ai:"Member states retain national veto over semiconductor export rules, delaying a common EU position on technology controls.",
      frag:"Reinforces fragmentation",
      fed:"Sets back digital sovereignty timeline"
    },
    {
      date:"13 Jun 2026",
      headline:"European Commission publishes new Capital Markets Union roadmap",
      ai:"A fresh roadmap proposes common rules for cross-border securities settlement, aiming to unlock pooled investment for green and tech industry by 2030.",
      frag:"Limited near-term effect if national implementation stalls",
      fed:"Modest positive — concrete step toward a unified capital market"
    },
    {
      date:"12 Jun 2026",
      headline:"Western Balkans summit reaffirms 2030 accession ambition",
      ai:"Leaders restate a target of opening final accession chapters with Montenegro and Albania, while flagging rule-of-law conditions still unmet by several candidates.",
      frag:"Enlargement remains uneven and slow",
      fed:"Positive — keeps the Balkans accession track alive"
    },
    {
      date:"11 Jun 2026",
      headline:"EU and US extend tech standards dialogue, no binding agreement",
      ai:"Talks on AI and data governance continue without a binding transatlantic framework, leaving the EU reliant on US cloud and AI infrastructure for now.",
      frag:"Confirms continued dependency on foreign technology",
      fed:"No immediate change — sovereignty push continues domestically"
    },
    {
      date:"10 Jun 2026",
      headline:"Ukraine accession talks: energy chapter provisionally closed",
      ai:"Negotiators provisionally close the energy chapter of Ukraine's accession talks, citing progress on grid synchronisation with the EU network.",
      frag:"Accession progress remains partial and dependent on external funding",
      fed:"Positive — concrete progress toward 2050 enlargement"
    },
    {
      date:"9 Jun 2026",
      headline:"Hungary blocks joint statement on foreign policy coordination",
      ai:"A member state veto again prevents a unified EU position, illustrating the limits of unanimity-based foreign policy decision-making.",
      frag:"Reinforces decision-making paralysis",
      fed:"Strengthens case for qualified-majority reform"
    }
  ]
};
