// Sample 2050 scenario data — illustrative, AI-assisted figures for prototype only.
// Real version would be regenerated daily from Eurostat + news/policy analysis.
//
// Population fields: pop2026 is the current population (Eurostat/UN estimates,
// ~2025). popFrag / popFed are 2050 endpoints under each scenario — the app
// interpolates linearly between pop2026 and the relevant endpoint for the
// selected year, so every point on the slider reflects a real trajectory
// rather than a single fixed "2050" number shown at every year.

window.EU2050_DATA = {

  // ---- Country-level data, keyed by ISO3 ----
  countries: {

    // --- Founding / current EU core ---
    "DEU": { name:"Germany", eu:true,
      fragScore:0.55, fedScore:0.95,
      fragNote:"Largest economy, but still bound by national vetoes on energy and tax policy. Industrial base increasingly reliant on imported chips and software platforms.",
      fedNote:"Anchors the federal capital market and co-funds the EU semiconductor and AI compute programme.",
      pop2026:"84.7M", popFrag:"82.2M", popFed:"89.8M" },
    "FRA": { name:"France", eu:true,
      fragScore:0.55, fedScore:0.95,
      fragNote:"Pushes 'strategic autonomy' rhetoric but national defence and energy policy remain largely separate from EU partners.",
      fedNote:"Co-leads federal defence procurement and the EU digital identity & cloud stack.",
      pop2026:"68.4M", popFrag:"66.4M", popFed:"72.5M" },
    "ITA": { name:"Italy", eu:true,
      fragScore:0.45, fedScore:0.85,
      fragNote:"High public debt limits fiscal room; depends on EU transfers without full integration of capital markets to absorb shocks.",
      fedNote:"Benefits from a shared federal debt instrument that lowers borrowing costs and funds green industry.",
      pop2026:"58.9M", popFrag:"54.2M", popFed:"60.7M" },
    "ESP": { name:"Spain", eu:true,
      fragScore:0.5, fedScore:0.88,
      fragNote:"Strong renewables growth, but exports of clean energy to the rest of Europe limited by unfinished interconnections.",
      fedNote:"Becomes a net energy exporter within a unified EU grid and capital market.",
      pop2026:"48.6M", popFrag:"44.7M", popFed:"50.1M" },
    "POL": { name:"Poland", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Frontline state on security policy, but defence spending and procurement remain mostly national.",
      fedNote:"Hosts federal defence-industrial hubs supplying a joint EU force structure.",
      pop2026:"36.6M", popFrag:"31.5M", popFed:"35.9M" },
    "NLD": { name:"Netherlands", eu:true,
      fragScore:0.6, fedScore:0.95,
      fragNote:"Home to critical chip-equipment supply chains, but export controls are negotiated bilaterally with the US, not as one EU bloc.",
      fedNote:"Chip-equipment leadership becomes the technical core of EU semiconductor sovereignty.",
      pop2026:"18.0M", popFrag:"17.5M", popFed:"19.1M" },
    "BEL": { name:"Belgium", eu:true,
      fragScore:0.55, fedScore:0.97,
      fragNote:"Hosts EU institutions, but Brussels' coordinating role outpaces actual policy integration.",
      fedNote:"Becomes the administrative and judicial seat of the federal government.",
      pop2026:"11.8M", popFrag:"11.4M", popFed:"12.5M" },
    "AUT": { name:"Austria", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Neutrality tradition keeps it outside deeper EU defence integration.",
      fedNote:"Joins a common federal defence framework while retaining a non-aligned diplomatic identity.",
      pop2026:"9.2M", popFrag:"8.9M", popFed:"9.8M" },
    "SWE": { name:"Sweden", eu:true,
      fragScore:0.55, fedScore:0.9,
      fragNote:"Strong on digital services but its tech sector still depends on US cloud infrastructure.",
      fedNote:"Anchors the EU's sovereign cloud and data-centre network.",
      pop2026:"10.6M", popFrag:"10.3M", popFed:"11.2M" },
    "FIN": { name:"Finland", eu:true,
      fragScore:0.55, fedScore:0.9,
      fragNote:"NATO member, but EU-level defence-industrial cooperation remains limited.",
      fedNote:"Telecom and cybersecurity expertise feeds the federal digital sovereignty programme.",
      pop2026:"5.6M", popFrag:"5.4M", popFed:"5.9M" },
    "DNK": { name:"Denmark", eu:true,
      fragScore:0.55, fedScore:0.9,
      fragNote:"Leads on offshore wind, but a unified EU energy market remains incomplete.",
      fedNote:"Offshore wind becomes part of a federation-wide energy grid and capital pool.",
      pop2026:"6.0M", popFrag:"5.8M", popFed:"6.4M" },
    "IRL": { name:"Ireland", eu:true,
      fragScore:0.45, fedScore:0.8,
      fragNote:"Corporate tax model under strain as national tax competition persists inside the bloc.",
      fedNote:"Adapts to a harmonised federal tax base while retaining a strong digital-services cluster.",
      pop2026:"5.4M", popFrag:"5.2M", popFed:"5.7M" },
    "PRT": { name:"Portugal", eu:true,
      fragScore:0.45, fedScore:0.82,
      fragNote:"Atlantic-facing data-cable hub, but digital infrastructure investment depends on non-EU capital.",
      fedNote:"Becomes a federal digital gateway, with EU-funded subsea cable and data infrastructure.",
      pop2026:"10.4M", popFrag:"9.6M", popFed:"10.7M" },
    "GRC": { name:"Greece", eu:true,
      fragScore:0.4, fedScore:0.8,
      fragNote:"Strategic Eastern Mediterranean position, but still recovering fiscal space limits its EU leverage.",
      fedNote:"Becomes a federal energy and logistics hub linking the EU to the Eastern Mediterranean and Balkans.",
      pop2026:"10.4M", popFrag:"9.6M", popFed:"10.7M" },
    "CZE": { name:"Czechia", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Strong manufacturing base, but tied to non-EU automotive and battery supply chains.",
      fedNote:"Battery and automotive sector integrates into a federal industrial policy.",
      pop2026:"10.9M", popFrag:"9.4M", popFed:"10.7M" },
    "SVK": { name:"Slovakia", eu:true,
      fragScore:0.45, fedScore:0.82,
      fragNote:"Energy dependency on external suppliers remains a vulnerability.",
      fedNote:"Plugged into a federation-wide energy security framework.",
      pop2026:"5.4M", popFrag:"4.6M", popFed:"5.3M" },
    "HUN": { name:"Hungary", eu:true,
      fragScore:0.35, fedScore:0.6,
      fragNote:"Frequently blocks common EU positions, deepening the bloc's decision-making paralysis.",
      fedNote:"Remains a member but with reduced veto power under federal qualified-majority rules.",
      pop2026:"9.6M", popFrag:"8.3M", popFed:"9.4M" },
    "ROU": { name:"Romania", eu:true,
      fragScore:0.45, fedScore:0.85,
      fragNote:"Key Black Sea security role, but defence integration with EU partners is still patchy.",
      fedNote:"Becomes a federal frontline hub bordering the newly acceded Moldova and Ukraine.",
      pop2026:"19.0M", popFrag:"16.3M", popFed:"18.6M" },
    "BGR": { name:"Bulgaria", eu:true,
      fragScore:0.4, fedScore:0.78,
      fragNote:"Lags on digital infrastructure investment relative to EU peers.",
      fedNote:"Receives federal cohesion funding to close the digital infrastructure gap.",
      pop2026:"6.4M", popFrag:"5.5M", popFed:"6.3M" },
    "HRV": { name:"Croatia", eu:true,
      fragScore:0.45, fedScore:0.82,
      fragNote:"Tourism-dependent economy exposed to external shocks with limited EU-level buffers.",
      fedNote:"Adriatic tourism and shipping integrate into a federal single market with shared risk pooling.",
      pop2026:"3.8M", popFrag:"3.3M", popFed:"3.7M" },
    "SVN": { name:"Slovenia", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Small open economy exposed to fragmented EU capital markets.",
      fedNote:"Gains from a single federal capital market reducing borrowing costs for small economies.",
      pop2026:"2.1M", popFrag:"1.8M", popFed:"2.1M" },
    "LTU": { name:"Lithuania", eu:true,
      fragScore:0.5, fedScore:0.88,
      fragNote:"Frontline state on Russia border security, reliant on NATO more than EU structures.",
      fedNote:"Integrated into a federal eastern defence shield alongside Poland and Finland.",
      pop2026:"2.9M", popFrag:"2.5M", popFed:"2.8M" },
    "LVA": { name:"Latvia", eu:true,
      fragScore:0.48, fedScore:0.85,
      fragNote:"Energy grid still synchronising away from non-EU networks.",
      fedNote:"Fully integrated into the federal Baltic energy grid.",
      pop2026:"1.9M", popFrag:"1.6M", popFed:"1.9M" },
    "EST": { name:"Estonia", eu:true,
      fragScore:0.6, fedScore:0.92,
      fragNote:"Digital governance leader, but its e-government model isn't yet an EU-wide standard.",
      fedNote:"Estonia's digital-ID model becomes the federal standard for all member states.",
      pop2026:"1.37M", popFrag:"1.2M", popFed:"1.3M" },
    "LUX": { name:"Luxembourg", eu:true,
      fragScore:0.55, fedScore:0.95,
      fragNote:"Financial hub benefits from EU access but national rules still fragment capital flows.",
      fedNote:"Becomes a key node in the unified federal capital markets union.",
      pop2026:"0.67M", popFrag:"0.65M", popFed:"0.71M" },
    "MLT": { name:"Malta", eu:true,
      fragScore:0.5, fedScore:0.85,
      fragNote:"Small state with limited leverage over EU-level digital and energy policy.",
      fedNote:"Gains proportionally stronger voice under federal small-state safeguards.",
      pop2026:"0.56M", popFrag:"0.52M", popFed:"0.58M" },
    "CYP": { name:"Cyprus", eu:true,
      fragScore:0.45, fedScore:0.8,
      fragNote:"Eastern Mediterranean energy finds remain entangled in bilateral disputes.",
      fedNote:"Federal foreign policy resolves regional disputes with a single EU negotiating voice.",
      pop2026:"0.92M", popFrag:"0.85M", popFed:"0.95M" },

    // --- Western Balkans: EU 2026, candidate/aspiring; federal-2050 members ---
    "SRB": { name:"Serbia", eu:false,
      fragScore:0.3, fedScore:0.78, fedNew:true,
      fragNote:"Accession talks remain stalled by rule-of-law concerns and balancing act between EU and other powers.",
      fedNote:"Joins the federation in 2030 alongside Albania and Moldova, integrating its energy grid and labour market with the EU.",
      pop2026:"6.6M", popFrag:"5.6M", popFed:"6.3M" },
    "ALB": { name:"Albania", eu:false,
      fragScore:0.32, fedScore:0.76, fedNew:true,
      fragNote:"Accession process moves slowly; economy remains only loosely linked to the single market.",
      fedNote:"Becomes a federal member state, with tourism and energy sectors fully integrated.",
      pop2026:"2.7M", popFrag:"2.3M", popFed:"2.6M" },
    "MNE": { name:"Montenegro", eu:false,
      fragScore:0.35, fedScore:0.8, fedNew:true,
      fragNote:"Furthest along in accession talks but full membership remains pending.",
      fedNote:"One of the earliest Balkan accessions, fully part of the federal single market by the 2030s.",
      pop2026:"0.62M", popFrag:"0.53M", popFed:"0.6M" },
    "MKD": { name:"North Macedonia", eu:false,
      fragScore:0.3, fedScore:0.76, fedNew:true,
      fragNote:"Name and constitutional disputes have repeatedly slowed its EU path.",
      fedNote:"Joins the federation, contributing to a fully connected Balkan energy and transport corridor.",
      pop2026:"1.83M", popFrag:"1.6M", popFed:"1.8M" },
    "BIH": { name:"Bosnia and Herzegovina", eu:false,
      fragScore:0.25, fedScore:0.7, fedNew:true,
      fragNote:"Complex internal governance structure remains the biggest obstacle to EU accession.",
      fedNote:"Joins later than its neighbours, with federal mediation helping resolve internal governance issues.",
      pop2026:"3.2M", popFrag:"2.7M", popFed:"3.1M" },
    "XKX": { name:"Kosovo", eu:false,
      fragScore:0.25, fedScore:0.68, fedNew:true,
      fragNote:"Recognition gaps among EU member states themselves slow any accession progress.",
      fedNote:"Recognition issues resolved within a federal framework, enabling full integration.",
      pop2026:"1.6M", popFrag:"1.4M", popFed:"1.5M" },

    // --- Ukraine & Moldova: candidates in 2026; federal-2050 new members ---
    "UKR": { name:"Ukraine", eu:false,
      fragScore:0.2, fedScore:0.75, fedNew:true,
      fragNote:"Reconstruction and accession remain heavily dependent on external (often non-EU) financing and security guarantees; population stays well below its pre-war level.",
      fedNote:"Joins the federation, bringing a large agricultural and tech-talent base and a fully rebuilt, EU-integrated industrial base. Federal reconstruction funding and coordinated return programmes bring much of the wartime refugee population back.",
      pop2026:"37.5M", popFrag:"34M", popFed:"40M" },
    "MDA": { name:"Republic of Moldova", eu:false,
      fragScore:0.28, fedScore:0.78, fedNew:true,
      fragNote:"Small economy, vulnerable to external pressure while accession talks proceed slowly.",
      fedNote:"One of the fastest accessions, fully integrated into the federal single market and energy grid.",
      pop2026:"2.4M", popFrag:"2.1M", popFed:"2.4M" },
    "GEO": { name:"Georgia", eu:false,
      fragScore:0.25, fedScore:0.78, fedNew:true,
      fragNote:"EU accession is slowed by geopolitical tensions and domestic reform challenges.",
      fedNote:"Joins the federation as a new eastern member, deepening EU energy and transport links with the South Caucasus.",
      pop2026:"3.7M", popFrag:"3.3M", popFed:"3.8M" },
    "ARM": { name:"Armenia", eu:false,
      fragScore:0.28, fedScore:0.78, fedNew:true,
      fragNote:"Continues building ties with the EU while balancing relations with Russia and regional security partners.",
      fedNote:"Becomes a federation partner, strengthening EU access to South Caucasus transport and digital corridors.",
      pop2026:"2.8M", popFrag:"2.5M", popFed:"2.9M" },
    "AZE": { name:"Azerbaijan", eu:false,
      fragScore:0.3, fedScore:0.78, fedNew:true,
      fragNote:"Energy and geopolitical tensions leave its EU path uncertain despite economic interest in closer ties.",
      fedNote:"Enters the federation with strategic energy and transport links to the Caspian and Black Sea regions.",
      pop2026:"10.2M", popFrag:"10.7M", popFed:"11.2M" },

    // --- Non-EU neighbours / not modelled as part of either scenario's core ---
    "GBR": { name:"United Kingdom", eu:false, fedNew:true,
      fragScore:0.5, fedScore:0.82,
      fragNote:"Remains outside the EU; closer alignment on some standards but no formal reintegration.",
      fedNote:"Rejoins in 2040 after a generation outside: a successful federation with a single capital market makes re-accession the pragmatic choice, and the City reintegrates as a federal financial centre.",
      pop2026:"69.5M", popFrag:"72M", popFed:"73M" },
    "CHE": { name:"Switzerland", eu:false,
      fragScore:0.5, fedScore:0.85, fedNew:true,
      fragNote:"Maintains bilateral arrangements rather than full integration.",
      fedNote:"Joins the federation, bringing financial expertise and deepening single market integration.",
      pop2026:"8.9M", popFrag:"9.2M", popFed:"9.6M" },
    "NOR": { name:"Norway", eu:false,
      fragScore:0.5, fedScore:0.85, fedNew:true,
      fragNote:"EEA member but outside core EU decision-making on digital and capital markets policy.",
      fedNote:"Joins the federation, integrating its energy resources into the federal grid and market.",
      pop2026:"5.6M", popFrag:"5.8M", popFed:"6.0M" },
    "ISL": { name:"Iceland", eu:false,
      fragScore:0.5, fedScore:0.85, fedNew:true,
      fragNote:"A near-term EU accession referendum puts Iceland on the fastest track among EFTA states, though full membership still awaits ratification.",
      fedNote:"Joins the federation early, alongside Montenegro, folding fisheries policy and Arctic energy security into the federal framework.",
      pop2026:"0.40M", popFrag:"0.42M", popFed:"0.43M" },
    "TUR": { name:"Turkey", eu:false,
      fragScore:0.35, fedScore:0.68, fedNew:true,
      fragNote:"Long-frozen accession process; relationship managed through customs union and migration deals.",
      fedNote:"Accedes last, in 2045, after a long convergence on rule-of-law and democratic standards; brings the federation's largest young workforce and an anchor on its southeastern flank.",
      pop2026:"86.1M", popFrag:"89.5M", popFed:"90.5M" }
  },

  // ---- Aggregate scenario stats shown in the stat strips ----
  // Not read at runtime (app.js computes these live from country-level data
  // and the year slider) — kept here as a human-readable snapshot of the
  // 2026 baseline and 2050 endpoints.
  stats: {
    frag: { pop2026:"450M", pop2050:"419M", members:"27", gdp2026:"18%", gdp2050:"10%" },
    fed:  { pop2026:"450M", pop2050:"721M", members:"43", gdp2026:"18%", gdp2050:"19%" }
  },

  // ---- Sample AI-generated daily signal feed ----
  // In production this is regenerated daily by an automated pipeline that
  // reads EU news/policy documents and tags each story's likely pull on each scenario.
  feed: [
      {
        "headline": "EU agrees landmark AI governance roadmap, but implementation timeline remains contested",
        "ai": "Commission and member states outline common AI liability and certification rules while national regulators still negotiate enforcement powers.",
        "frag": "National regulators keep enforcement power, so AI oversight stays a patchwork despite the common roadmap.",
        "fed": "Lays the technical groundwork for the single federal AI governance regime Scenario B assumes by 2050."
      },
      {
        "headline": "European Parliament backs strengthened carbon border levy for imported steel and chemicals",
        "ai": "A new CBAM proposal seeks tighter enforcement on high-carbon imports, raising pressure on industry and trading partners.",
        "frag": "Raises trade friction that a fragmented, unanimity-bound EU is poorly placed to manage collectively.",
        "fed": "Aligns external carbon pricing with the federal green-industrial strategy, a concrete step toward the unified market."
      },
      {
        "headline": "EU foreign ministers approve a joint connectivity package for the Western Balkans",
        "ai": "Funding and regulatory alignment for cross-border energy and data corridors are agreed, signalling deeper integration with candidate neighbours.",
        "frag": "Funding is agreed centrally but rollout still depends on separate national implementation plans.",
        "fed": "Accelerates the federation’s eastern enlargement and infrastructure integration"
      },
      {
        "headline": "Council debates migration and energy solidarity rules ahead of summer peak",
        "ai": "Member states are split over mandatory burden-sharing and fast-track renewable power sharing, exposing persistent EU coordination gaps.",
        "frag": "A textbook case of the coordination gaps that keep crisis response stuck at the national level.",
        "fed": "Reinforces the need for a federal emergency energy and asylum framework"
      },
      {
        "headline": "Council fails to agree on unified chip-export control list",
        "ai": "Member states retain national veto over semiconductor export rules, delaying a common EU position on technology controls.",
        "frag": "Keeps chip-export policy fragmented across 27 capitals, reinforcing external dependence on US and Chinese supply chains.",
        "fed": "Sets back the digital-sovereignty timeline the federal scenario relies on for a joint EU chip strategy."
      },
      {
        "headline": "European Commission publishes new Capital Markets Union roadmap",
        "ai": "A fresh roadmap proposes common rules for cross-border securities settlement, aiming to unlock pooled investment for green and tech industry by 2030.",
        "frag": "Only a modest near-term effect if national implementation stalls, as it has with previous CMU roadmaps.",
        "fed": "A concrete, incremental step toward the unified capital market that underpins the federal economic model."
      },
      {
        "headline": "Western Balkans summit reaffirms 2030 accession ambition",
        "ai": "Leaders restate a target of opening final accession chapters with Montenegro and Albania, while flagging rule-of-law conditions still unmet by several candidates.",
        "frag": "Enlargement stays uneven and slow, with individual candidates progressing at very different speeds.",
        "fed": "Keeps the Balkans accession track alive and on schedule for the federation’s enlarged 2050 membership."
      },
      {
        "headline": "EU and US extend tech standards dialogue, no binding agreement",
        "ai": "Talks on AI and data governance continue without a binding transatlantic framework, leaving the EU reliant on US cloud and AI infrastructure for now.",
        "frag": "Confirms continued EU dependency on foreign cloud and AI infrastructure with no near-term fix in sight.",
        "fed": "No immediate change, but adds urgency to the domestic federal push for EU-owned compute and cloud capacity."
      },
      {
        "headline": "Ukraine accession talks: energy chapter provisionally closed",
        "ai": "Negotiators provisionally close the energy chapter of Ukraine's accession talks, citing progress on grid synchronisation with the EU network.",
        "frag": "Accession progress remains partial and still dependent on external reconstruction funding.",
        "fed": "Concrete, chapter-by-chapter progress toward Ukraine’s full federal membership by the mid-2030s."
      },
      {
        "headline": "Hungary blocks joint statement on foreign policy coordination",
        "ai": "A member state veto again prevents a unified EU position, illustrating the limits of unanimity-based foreign policy decision-making.",
        "frag": "Another veto shows exactly why unanimity rules keep the Union unable to act with one voice.",
        "fed": "Strengthens the case for the qualified-majority reform central to how the federation makes decisions."
      }
    ]
};
